#!/bin/bash

total=$( ls -l ../timing_histogram/out/*.hist | wc -l)
total=$(( $total+$(ls -l ../timing_histogram_mem/out/*.hist | wc -l ) ))
total=$(( $total+$(ls -l ../timing_histogram_mem/out_fix/*.hist | wc -l ) ))
threads=8

while [ $threads > 1 ]
do
count=$(cat combined_parse_*.log | grep "Parsing starts for" | wc -l)
threads=$(ps aux | grep "./generate_histogram_csv.py" | wc -l)

if [ $threads > 1 ]
then
    echo -ne "count: $count total: $total ($(($threads-1)) threads are running)"\\r
else
    echo " done!"
fi
sleep 5
done
